[package]
name = "pons"
version = "0.1.0"
authors = ["Chen-Pang He (https://jdh8.org)"]
edition = "2021"
description = "Rust package for contract bridge"
repository = "https://github.com/jdh8/pons"
categories = ["game-development"]
keywords = ["bridge"]

[dependencies]
bitflags = "2.0.2"
dds-bridge = "0.9.1"
rand = "0.8.5"

[dev-dependencies]
nalgebra = "0.32.6"
