[package]
name = "pons"
version = "0.4.0"
authors = ["Chen-Pang He (https://jdh8.org)"]
edition = "2021"
description = "Rust package for contract bridge"
repository = "https://github.com/jdh8/pons"
license = "Apache-2.0"
categories = ["game-development"]
keywords = ["bridge"]

[dependencies]
bitflags = "2.9.1"
dds-bridge = "0.11.1"
rand = "0.9.1"
thiserror = "2.0.12"

[dev-dependencies]
approx = "0.5.1"
nalgebra = "0.33.0"
