#!/bin/sh
# ab-landy-strength-residue.sh — §N1q residue: three independent knobs, each
# against the SAME control (`main`, §N1q shipped default-on, c3bb94a7), so one
# `base` arm serves all three.
#
#   JOBS=24 BOARDS=4608000 setsid nohup scripts/idle-run.sh \
#       scripts/ab-landy-strength-residue.sh ab-results/landy-strength4 \
#       >ab-results/landy-strength4.log 2>&1 < /dev/null & disown
#
# Four arms, SEQUENTIAL, one SEED_BASE.  Pre-registrations, predictions and
# falsifiers in docs/one-notrump-competitive.md §N1q ("The residue arms").
#
#   base  today's `main`
#   nv    `--ns-landy-strength-nv-invite`: vulnerable, the 8-9 short-major hand
#         keeps the values `X`.  Reads `vulnerable()`, so its `none` cell must
#         show ZERO divergent boards — a free build check.
#   strx  `--ns-landy-strength-doubles`, now with its two tails authored
#         (`2♥ (2♠) X (XX)`, `2♥ (2♠) X - 3m (3♠)`).  Adds doubles: plain
#         arbitrates.
#   rail  `--ns-landy-recue-signoff`: responder sits `2NT - 3♣ - 3M - 3NT -`.
#
# Each verdict is its own: the knobs touch disjoint nodes and none is measured
# on top of another.  Do NOT edit this file while it runs (dash re-reads it).
#
R=${1:?usage: ab-landy-strength-residue.sh RESULTS_DIR}
BUILD_EXTRA='--example ab-dump-sd --example probe-divergence'
. "$(dirname "$0")/ab-lib.sh"

SEED_BASE=$(seed_for landy-strength-residue)
log "=== landy-strength-residue SEED_BASE=$SEED_BASE sha=$SHA shards=$SHARDS x $PER_SHARD bd/arm/vul"

# Vulnerable first: it is the cell `nv` exists for.  `nv`'s `none` cell is
# byte-identical by construction, so it runs LAST and tolerantly — under
# `set -e` a tool that balks at zero divergent boards must not cost the rest.
for v in both none; do
    arm base "$v" --filter-landy
    arm strx "$v" --filter-landy --ns-landy-strength-doubles
    arm rail "$v" --filter-landy --ns-landy-recue-signoff
    ons='strx rail'
    if [ "$v" = both ]; then
        arm nv "$v" --filter-landy --ns-landy-strength-nv-invite
        ons='nv strx rail'
    fi
    for on in $ons; do
        gatepair "$on" base "$v"
        diffpair "$on" base "$v"
    done
done

for v in both none; do
    for on in nv strx rail; do
        [ "$on$v" = nvnone ] && continue
        sddiff "$on" base "$v"
    done
done

arm nv none --filter-landy --ns-landy-strength-nv-invite
gatepair nv base none || log "nv none gate exited non-zero — expected iff zero divergent boards; read $R/gate.nv.vs.base.none.txt"

log "landy-strength-residue done"
