#!/bin/sh
# ab-landy-strength-residue.sh — §N1q residue: three independent knobs, each
# against the SAME control (`main`, §N1q shipped default-on, c3bb94a7), so one
# `base` arm serves all three.
#
#   JOBS=24 BOARDS=4608000 setsid nohup scripts/idle-run.sh \
#       scripts/ab-landy-strength-residue.sh ab-results/landy-strength5 \
#       >ab-results/landy-strength5.log 2>&1 < /dev/null & disown
#
# Four arms, SEQUENTIAL, one SEED_BASE.  Pre-registrations, predictions and
# falsifiers in docs/one-notrump-competitive.md §N1q ("The residue arms").
#
#   base  today's `main`
#   nv    `--ns-landy-strength-nv-invite`: vulnerable, the 8-9 short-major hand
#         keeps the values `X`.  Reads `vulnerable()`, so its `none` cell must
#         show ZERO divergent boards — a free build check.
#   strx  `--ns-landy-strength-doubles`, now with its two tails authored
#         (`2♥ (2♠) X (XX)`, `2♥ (2♠) X - 3m (3♠)`).  Adds doubles: plain
#         arbitrates.
#   rail  `--ns-landy-recue-signoff`: responder sits `2NT - 3♣ - 3M - 3NT -`.
#
# Each verdict is its own: the knobs touch disjoint nodes and none is measured
# on top of another.  Do NOT edit this file while it runs (dash re-reads it).
#
# RUN 4 VERDICT (2026-09-21, ab-results/landy-strength4, seed 1789929046, sha
# a28d2784, 4.608M bd/arm/vul; every isolation gate 0 foreign, nv/none 0
# divergent boards):
#   rail  SHIPPED default-on.  plain +0.00116 ±0.00013 both / +0.00095 ±0.00012
#         NV; PD +0.00134 / +0.00117; sd-lead +0.0010 / +0.0008 plain.
#   strx  SHIPPED default-on.  plain +0.00004 ±0.00010 both (non-loss) /
#         +0.00010 ±0.00010 NV (win); sd-lead positive in all four cells.
#   nv    BUILD DEFECT, not a verdict.  plain −0.00027 ±0.00045: the `2♠ → X`
#         cell read +9,238 ±1,609 as predicted, and 9,529 seven-counts the
#         `X` (`hcp(8..)`) refuses fell to `Pass` for −9,234 (+1,209 to `2♦`,
#         −1,252).  Repaired (`| hcp(..=7)`) and re-armed below as `nv2`.
#
# With rail and strx on by default, the control and the flags changed: `base`
# here is the *new* `main`, and the old arms are spelled with `--no-…` on the
# control side.  Runs 5+ build only `base2` / `nv2`, both-vul first.
#
# RUN 5 VERDICT (2026-09-21, ab-results/landy-strength5, seed 1789977169):
#   nv2   SHIPPED default-on.  both-vul plain +0.0018 ±0.0003 on 9,623 boards,
#         PD +0.0000 ±0.0004; sd-lead plain +0.0013 ±0.0004 (falsifier: CI-clear
#         negative — did not fire); NV 0 divergent.  The flag flipped with it:
#         `base2` now carries `--no-ns-landy-strength-nv-invite`.
#
R=${1:?usage: ab-landy-strength-residue.sh RESULTS_DIR}
BUILD_EXTRA='--example ab-dump-sd --example probe-divergence'
. "$(dirname "$0")/ab-lib.sh"

SEED_BASE=$(seed_for landy-strength-residue)
log "=== landy-strength-residue SEED_BASE=$SEED_BASE sha=$SHA shards=$SHARDS x $PER_SHARD bd/arm/vul"

# Run 4's arms (`nv` / `strx` / `rail` against `base`) are retired with the
# flip: their ON flags no longer exist.  The run-4 loop is in git at a28d2784.
for v in both none; do
    arm base2 "$v" --filter-landy --no-ns-landy-strength-nv-invite
    arm nv2   "$v" --filter-landy
    # `none` must read zero divergent boards; the gate may balk at that.
    gatepair nv2 base2 "$v" || log "nv2 $v gate exited non-zero — read $R/gate.nv2.vs.base2.$v.txt"
    [ "$v" = both ] || continue
    diffpair nv2 base2 "$v"
    sddiff   nv2 base2 "$v"
done

log "landy-strength-residue done"
